name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "8"
      - name: Build with Maven
        run: mvn -B install site --file pom.xml
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: lime-openfl-maven-plugin
          path: target/lime-openfl-maven-plugin-*.jar
          if-no-files-found: error
      - name: Upload API Documentation
        uses: actions/upload-artifact@v2
        with:
          name: lime-openfl-maven-plugin-javadoc
          path: target/site/apidocs/
          if-no-files-found: error
      - name: Upload Site
        if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: target/site
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.4
      - name: "Build Sample: OpenFL"
        working-directory: samples/openfl-project
        run: mvn -B compile --file pom.xml
      - name: "Build Sample: Lime"
        working-directory: samples/lime-project
        run: mvn -B compile --file pom.xml
      - name: "Build Sample: Lime (Unconfigured)"
        working-directory: samples/unconfigured-lime-project
        run: mvn -B compile --file pom.xml
      - name: "Build Sample: Feathers UI"
        working-directory: samples/feathersui-project
        run: mvn -B compile --file pom.xml
      - name: "Build Sample: OpenFL with project.xml"
        working-directory: samples/openfl-project-with-xml
        run: mvn -B test --file pom.xml
      - name: "Build Sample: OpenFL with Tests"
        working-directory: samples/openfl-project-with-tests
        run: mvn -B test --file pom.xml
